# Generated by Django 3.0.4 on 2020-10-11 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_video', models.FileField(upload_to='')),
                ('abnormal_type', models.CharField(max_length=20)),
                ('edited_date', models.DateTimeField()),
                ('full', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='api.Full')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
